services:

  kbn-ror:
    image: beshultd/kibana-readonlyrest:8.14.3-ror-latest
    user: "0:0"
    ports: 
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=https://es-ror:9200
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=kibana
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
      - I_UNDERSTAND_IMPLICATION_OF_KBN_PATCHING=yes
      - readonlyrest_kbn__cookiePass=abcd1234abcd1234abcd1234abcd1234
    depends_on:
      - es-ror

  es-ror:
    image: beshultd/elasticsearch-readonlyrest:8.14.3-ror-latest
    user: "0:0"
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - I_UNDERSTAND_IMPLICATION_OF_ES_PATCHING=yes
