openapi: 3.0.3
info:
  title: ReadonlyREST API
  description: The API is designed for ReadonlyREST Kibana plugin users.
  version: 1.0.0

paths:
  /api/ror/settings:
    post:
      summary: Configuring in-index Main Settings
      description: The endpoint can be used to configure Main Settings.
      tags:
        - Main Settings
      parameters:
        - $ref: '#/components/parameters/XRorCorrelationIdHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMainSettingsRequest'
      responses:
        200:
          description: Returns a status of updating Main Settings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateMainSettingsResponse'
              examples:
                UpdateMainSettingsSuccessResponse:
                  $ref: "#/components/examples/UpdateMainSettingsSuccessResponse"
                UpdateMainSettingsFailedResponse:
                  $ref: "#/components/examples/UpdateMainSettingsFailedResponse"
        403:
          description: The request was forbidden by ReadonlyREST's ACL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenRorResponse'
              examples:
                NoAclBlockWasMatchedForbiddenResponseExample:
                  $ref: "#/components/examples/NoAclBlockWasMatchedForbiddenResponseExample"
                ForbidBlockMatchedResponseExample:
                  $ref: "#/components/examples/ForbidBlockMatchedResponseExample"
                TestSettingsNotConfiguredForbiddenResponseExample:
                  $ref: "#/components/examples/TestSettingsNotConfiguredForbiddenResponseExample"
                ImpersonationNotSupportedResponseExample:
                  $ref: "#/components/examples/ImpersonationNotSupportedResponseExample"
                ImpersonationNotAllowedResponseExample:
                  $ref: "#/components/examples/ImpersonationNotAllowedResponseExample"
                RorIsNotStartedYetResponseExample:
                  $ref: "#/components/examples/RorIsNotStartedYetResponseExample"
                RorFailedToStartResponseExample:
                  $ref: "#/components/examples/RorFailedToStartResponseExample"
                CannotSaveClusterWideSettingsOnFreeLicense:
                  $ref: "#/components/examples/CannotSaveClusterWideSettingsOnFreeLicense"

components:
  securitySchemes:
    http:
      type: http
      scheme: basic

  schemas:
    ForbiddenRorResponse:
      type: object
      required:
        - error
        - status
      properties:
        error:
          type: object
          required:
            - type
            - reason
            - due_to
          properties:
            type:
              type: string
              enum:
                - forbidden_response
            reason:
              type: string
              enum:
                - forbidden
            due_to:
              type: array
              description: |
                It's an array of causes why ReadonlyREST's ACL forbade the request. 
                WARNING: Please notice, that one element array ES used to print as a string!!!
              items:
                type: string
                enum:
                  - OPERATION_NOT_ALLOWED
                  - FORBIDDEN_BY_BLOCK
                  - TEST_SETTINGS_NOT_CONFIGURED
                  - IMPERSONATION_NOT_SUPPORTED
                  - IMPERSONATION_NOT_ALLOWED
                  - READONLYREST_NOT_READY_YET
                  - READONLYREST_NOT_ENABLED
                  - READONLYREST_FAILED_TO_START
                  - cannotSaveClusterWideSettingsOnFreeLicense
        status:
          type: number
          example: 403

    XRorCorrelationId:
      type: string
      description: "Correlation ID to correlate requests/responses logs within one ROR KBN session"
      example: "CED054A0-9881-401E-AEED-4FB4C5915DD6"

    UpdateMainSettingsRequest:
      type: object
      required:
        - settings
      properties:
        settings:
          type: string
          description: "ReadonlyREST main settings YAML"
          example: |
            readonlyrest:\\r\\n    access_control_rules:\\r\\n\\r\\n    - name: | \\""Require HTTP Basic | Auth\\""\\r\\n      type: allow\\r\\n      indices: | [\\""test\\""]\\r\\n\\r\\n    - name: | \\""other\\""\\r\\n      auth_key: \\""admin:test\\""

    UpdateMainSettingsResponse:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: string
          description: Update Main Settings status
          enum:
            - ok
            - ko
        message:
          type: string
          description: Human readable message

  parameters:
    XRorCorrelationIdHeader:
      name: X-ROR-Correlation-ID
      in: header
      required: false
      description: ID to correlate requests/reponses logs within one ReadonlyREST KBN session
      schema:
        $ref: '#/components/schemas/XRorCorrelationId'

  examples:
    NoAclBlockWasMatchedForbiddenResponseExample:
      summary: No ACL block was matched
      value:
        status: forbidden
        message: 'No ACL block was matched'

    ForbidBlockMatchedResponseExample:
      summary: Request was forbidden by matching a block with "forbid" type
      value:
        status: forbidden
        message: 'Request was forbidden by matching a block with "forbid" type'

    TestSettingsNotConfiguredForbiddenResponseExample:
      summary: Request was forbidden because impersonation feature is disabled when Test Settings are not configured
      value:
        status: forbidden
        message: "Request was forbidden because impersonation feature is disabled when Test Settings are not configured"

    ImpersonationNotSupportedResponseExample:
      summary: No block was matched and at least one block has rule which doesn't support impersonation
      value:
        status: forbidden
        message: "No block was matched and at least one block has rule which doesn't support impersonation"

    ImpersonationNotAllowedResponseExample:
      summary: User has no impersonation permissions
      value:
        status: forbidden
        message: "User has no impersonation permissions"

    RorIsNotStartedYetResponseExample:
      summary: ReadonlyREST was not started yet
      value:
        status: forbidden
        message: "ReadonlyREST was not started yet"

    RorFailedToStartResponseExample:
      summary: ReadonlyREST failed to start
      value:
        status: forbidden
        message: "ReadonlyREST failed to start"

    CannotSaveClusterWideSettingsOnFreeLicense:
      summary: Cannot save cluster-wide settings on Free license
      value:
        status: forbidden
        message: "Cannot save cluster-wide settings on Free license"

    UpdateMainSettingsSuccessResponse:
      summary: Main settings updated with success
      value:
        status: ok
        message: "updated settings"

    UpdateMainSettingsFailedResponse:
      summary: Main settings update failed
      value:
        status: ko
        message: "Cannot save new settings"
security:
  - http: []